# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20161016_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='timestamp',
            new_name='created',
        ),
    ]
