# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20161017_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.ForeignKey(on_delete=videos.models.Category, to='videos.Video'),
        ),
    ]
