# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20161017_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='/myproject/static/img/categories/'),
        ),
        migrations.AlterField(
            model_name='videoimage',
            name='image',
            field=models.ImageField(upload_to='/myproject/static/img/videos/'),
        ),
    ]
