# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20161017_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='img/category_img'),
        ),
        migrations.AlterField(
            model_name='videoimage',
            name='image',
            field=models.ImageField(upload_to='img/video_img'),
        ),
    ]
