# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20161017_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videoimage',
            name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='picture_url',
            new_name='video_img_url',
        ),
        migrations.AddField(
            model_name='category',
            name='category_img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
        migrations.DeleteModel(
            name='VideoImage',
        ),
    ]
