# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20161019_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_img_url',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=240),
        ),
    ]
